spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: 123456
server:
  port: 8080
eureka:
  client:
    registerWithEureka: false       #禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/  #服务注册中心的地址
  server:
    renewalPercentThreshold: 0.49