name: zhangsan
age: 18
sex: 女
#开放所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    host: 134.175.134.80
    port: 5672
    username: root
    password: dhcc2018